# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
symbol = '👾 '
pyenv_version_name = true

[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
ignore_branches = []

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_status]
conflicted = '🏳'
ahead = 'ahead'
behind = 'behind'
diverged = 'diverged'
up_to_date = '✓'
untracked = 'untracked'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = 'renamed'
deleted = '🗑'

[time]
disabled = false
format = '[ $time ]($style) '
time_format = '%R'
utc_time_offset = 'local'
